### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by nunojesus** [vergecurrency/vWallet#10]
Hi, How are you?
Im a graphic designer that like to help projects in opensource for free, so if you like I can contribute with graphic designs,, I can make you a logotype for this project if you want. So if you need some design just say it.

Greetings!
Nuno Jesus

**Comment by marpme** [comment]
Hey nuno,

we would really appreciate any kind of help, even a logo design would be cool!
Looking forward to see some great designs 👍 

Greeting marpme

**Comment by marpme** [comment]
Okay I gonna close that one, as it seems to be not longer maintained. Feel free to message me if you are still willing to create one, so that I can reactive this issue.
