### ISSUE TITLE
Unencrypted wallet asking for passphrase

### ISSUE THREAD

**Issue by Positivism** [vergecurrency/vWallet#11]
Generated a new wallet.dat just to ensure it wasn't encrypted.
<img width="642" alt="screen shot 2018-06-23 at 11 15 37 am" src="https://user-images.githubusercontent.com/35063339/41811092-ef99caf6-76d6-11e8-9802-95dd58a93c5f.png">
It requires me to unlock a wallet never locked/encrypted to send/receieve etc.

OS: High Sierra

**Comment by marpme** [comment]
Know bug and will be fixed within the first iteration

**Comment by marpme** [comment]
We will close this issue as it was replaced by #39. It's more describing what we want to have at the end. Please comment there if there's something unclear or not the way should be. Thank you for your support.
