### ISSUE TITLE
Notifications display inaccurate data.

### ISSUE THREAD

**Issue by Positivism** [vergecurrency/vWallet#12]
<img width="459" alt="screen shot 2018-06-23 at 11 18 42 am" src="https://user-images.githubusercontent.com/35063339/41811103-3c6a6d72-76d7-11e8-90c4-c7126f862b1c.png">

I have 0 transactions.
Verge is roughly 2 cents.
Market-cap is roughly 350m.

**Comment by marpme** [comment]
It's currently just placeholding data. For later we will implement some kind of mechanism to automatically track some things locally. - need to implement this in the upcoming iteration 🤓

**Comment by Positivism** [comment]
Just a suggestion, for mooning make it based on 24h price percentage movement.

**Comment by marpme** [comment]
Good Idea, will take some level based curves for the other two notifications.
Something like this:

> It's quite common to use a square relation.
`level = constant * sqrt(XP)`

| Level  | Transactions |
| - | ------------- |
| 1  | 0  |
| 2 | 10  |
| 3  | 30 |
| 4 | 60  |
| 5 | 100  |

Additionally we could think of an percentage for the upcoming goal

**Comment by Positivism** [comment]
Would be an interesting concept to do something like that for the amount of XVG as well, encourage people to hold. 

"My XVG wallet is lvl 10" Being xxxxx xvg or whatever.
But yeah I like the idea.

Edit: sqrt(transactions)+sqrt(balance) or something along those lines.

**Comment by marpme** [comment]
Will be done within another milestone.

**Comment by marpme** [comment]
Notifications will come with the new light client #62
