### ISSUE TITLE
Max send amount

### ISSUE THREAD

**Issue by Positivism** [vergecurrency/vWallet#13]
On the send verge model have the max send amount listed floating right to the transaction fee or add a max send button of some sort. (Balance-TransactionFee)

Useful for people trying to clear their wallets when moving to another device and don't wish to hassle with the .dat.

**Comment by Positivism** [comment]
<img width="1149" alt="screen shot 2018-06-23 at 8 39 30 pm" src="https://user-images.githubusercontent.com/35063339/41814767-983c217e-7725-11e8-8297-385756b36510.png">

**Comment by Positivism** [comment]
Something along those lines, maybe with a margin/padding-right: 5px or something if you don't like that slight overhang.

**Comment by Positivism** [comment]
<img width="484" alt="screen shot 2018-06-23 at 8 42 48 pm" src="https://user-images.githubusercontent.com/35063339/41814781-082b4244-7726-11e8-98ff-5d627784d09d.png">
10 px margin-right did the trick.
I could do a pull request.

Edit: Maybe not, typescript even changes html? Looks like XML tags with css class names. 🤔

**Comment by marpme** [comment]
Well sure you can create a pull-request and you are completely right that those Typescript files do have HTML included. Well finally - there you can add the 10 px margin and at the best do it in some kind of css class.
