### ISSUE TITLE
Deny negative values.

### ISSUE THREAD

**Issue by Positivism** [vergecurrency/vWallet#25]
<img width="578" alt="screen shot 2018-07-10 at 12 01 30 pm" src="https://user-images.githubusercontent.com/35063339/42522588-7687fe24-8439-11e8-9e7a-020b8a57f524.png">

Pretty self-explanatory, and when hitting send-max a -0.1 is put for input when your balance is 0;

**Comment by SwenVanZanten** [comment]
Good catch 👍 thank you

**Comment by SwenVanZanten** [comment]
@Positivism we're removing the possibility to open the send panel when having less XVG then the fee.
So I'm closing this issue 😉

**Comment by marpme** [comment]
Fixed with #30

**Comment by Positivism** [comment]
What if you have a balance and input a negative value as the send-amount?

**Comment by SwenVanZanten** [comment]
@Positivism isn’t possible 🙂 or if so provide a reproduction please😊

**Comment by Positivism** [comment]
Put a change event on the input and if input.value <0 change to 0.

**Comment by SwenVanZanten** [comment]
This is already the case.
Please take look at https://github.com/vergecurrency/vWallet/pull/34
It's not possible to type in something less then 0

**Comment by marpme** [comment]
And from a technical perspective, even if you get access to this window by "reverse-engineering" the entire thing, then you still won't be able to send it.

**Comment by Positivism** [comment]
Just for aesthetical reasons @marpme.
