### ISSUE TITLE
Duplicated Code

### ISSUE THREAD

**Issue by marpme** [vergecurrency/vWallet#37]
Having two times sendTransaction feature isn't nice.
So we are going to abstract handling for sending transactions

**Comment by Positivism** [comment]
You could refactor or have it fill out the send-address field with the donation address and open that view.

**Comment by marpme** [comment]
It's not really something that is visually duplicated (more like we have to versions of sending vergies around) and that's not cool in no way. 

So we want instantly get rid off this cluttered shit.

**Comment by marpme** [comment]
Fixed <3
