### ISSUE TITLE
Force User to create a password for their wallet

### ISSUE THREAD

**Issue by marpme** [vergecurrency/vWallet#39]
**Is your feature request related to a problem? Please describe.**
when opening the wallet with an unencrypted wallet file, then you are still required to enter a password
for using all necessary functionalities of a standard wallet.

**Describe the solution you'd like**
The best would be to show the already available screen (Tour.tsx / Password) to update your wallet with a password set by the users. This should be required as long as the user has an unencrypted wallet.

**Requirements:**
* Password is being set once 
* Once you've entered your password into the wallet your session **won't be revoked** automatically.
   * Unless the user locks it
* Password is required with each restart (lock wallet before closing it)

Related issues: #11 

_Edit: Requirements added_

**Comment by Positivism** [comment]
This is going to lead to a lot of lost wallets @marpme

**Comment by marpme** [comment]
@positivism why do you think that? Just because people forget the password?

**Comment by Positivism** [comment]
Yep, when people are forced to make a password for things they either use the same one they use for everything or quickly try to think of a new easy to remember one which they forget.

**Comment by marpme** [comment]
We are as community and project committed to provide an enhanced security wallet, thus we have to include some kind of mechanism for authenticating users who want to access the wallets.

If you have a better idea how to do that well then please add this, 
we are open for new ideas in that terms.

**Comment by Positivism** [comment]
Keep it optional, an encrypted wallet.dat is pretty useless outside access to the keypool by means of security anyhow.

**Comment by marpme** [comment]
The community has decided to keep it with password as default 👍

**Comment by marpme** [comment]
Will be done within the first beta. Definitely needed.

**Comment by Positivism** [comment]
Default as in required or default as in option to disable it.

**Comment by marpme** [comment]
as required and no opt-in nor opt-out. You'll have to type in your password once at start up.
