### ISSUE TITLE
[macOS] VERGEd executable not startable

### ISSUE THREAD

**Issue by Positivism** [vergecurrency/vWallet#4]
Latest up to date version of tor installed.
Used `brew install tor`
Started the tor daemon

<img width="554" alt="screen shot 2018-06-13 at 7 31 57 pm" src="https://user-images.githubusercontent.com/35063339/41383793-7b9c30aa-6f40-11e8-92b3-b5d1bd0c1889.png">

And I get the error
 ``` 
[error] Error: connect ECONNREFUSED 127.0.0.1:20102
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[error] Error: connect ECONNREFUSED 127.0.0.1:9089
 - Are you running `tor`?
```

Running MacOS HighSierra

**Comment by marpme** [comment]
You need to have a local verge deamon running on your mac for the dev version.

like so `./src/VERGEd -rpcuser="kyon" -rpcpassword="lolcat" -printtoconsole`
You can also change your user via editing:

https://github.com/vergecurrency/vWallet/blob/develop/src/stores/VergeClient.ts#L12-L15

And afterwards you will be able to start the wallet by typing `yarn && yarn dev`

There are going to be errors at the beginning that say couldn't connect to `127.0.0.1:20102`
That's normal as he is retrying to reconnect until he can for the sake of the long loading session!

**Comment by marpme** [comment]
We have to change this problem into a `config.json` that the devs have to fill up and enhance the logging at this point so you really know what going on.

**Comment by Positivism** [comment]
There's a VERGEd in /build, not /src.
When trying to execute it.
`dyld: Library not loaded: /usr/local/opt/miniupnpc/lib/libminiupnpc.17.dylib`
Looks like a dependency issue. I tried:
`brew reinstall libpng`
To no avail.

I'll try grabbing the normal VERGEd from the verge repo.

**Comment by marpme** [comment]
That's weird, can you tell me on what exact OS you are? (Beta, stable version number)

**Comment by Positivism** [comment]
High Sierra 10.13.5 (Latest stable)

**Comment by marpme** [comment]
Maybe the problem is that I configured the male process with gui but just shipped the deamon, but for me everything just works fine 🤔

**Comment by marpme** [comment]
maybe you have to install `brew install boost@1.60`

**Comment by Positivism** [comment]
`CWarning: boost@1.60 1.60.0 is already installed and up-to-date`

**Comment by marpme** [comment]
Well, you could try to build the VERGEd on your own by checking out the verge repository and following the build process.

Otherwise I cannot help anymore as this seems to be a verge-core issue.

I've recompiled it freshly, maybe this works for you.
[VERGEd.zip](https://github.com/vergecurrency/vWallet/files/2106736/VERGEd.zip)

**Comment by Positivism** [comment]
Thanks, I purged all my verge build files and executables awaiting the rebase. I'll try it out and let you know.

**Comment by Positivism** [comment]
`dyld: Library not loaded: /usr/local/opt/miniupnpc/lib/libminiupnpc.17.dylib`
Same issue, quite odd as I've run VERGEd plenty of times.

**Comment by Positivism** [comment]
I have a verge daemon running on a remote server, perhaps in the node config I could change it to connect to that instead?

**Comment by marpme** [comment]
```
# Remove any old qt5 lingering around
brew uninstall qt5

# Make sure we have the C libs we need
brew install boost@1.60 pkg-config automake

# Install some deps
brew install qt@5.5 protobuf miniupnpc openssl qrencode berkeley-db4 zlib libevent

# Make sure our stuff is linked in our path
brew link automake autoconf
```
~ I've used that `vergeClone/building/mac/requirement.sh && vergeClone/building/mac/build.sh`, maybe that will do the trick? As I see that it is installing the miniupnpc lib

**Comment by Positivism** [comment]
Doing that made a dependency issue with launching verge normally, I'm just going to wait for the rebase and for this project to get out of its alpha stage as the readme is also rather confusing and contradictory. More questions than answers.
