### ISSUE TITLE
Fix the header layout in large window

### ISSUE THREAD

**Issue by SwenVanZanten** [vergecurrency/vWallet#40]
**Describe the bug**
The header should have an more elegant feel to it when resizing the window.
- Now the buttons will get more margin between each other.
- The header height increases.
- And the menu button goes to the bottom slightly.

**To Reproduce**
Resize the window and see the buttons/logo dance.

**Expected behavior**
Don't resize the button margins.
Don't resize the header height.
Don't move the menu button on resize.

**Screenshots**
<img width="2011" alt="schermafbeelding 2018-07-19 om 19 07 17" src="https://user-images.githubusercontent.com/3099122/42958850-09feba2c-8b87-11e8-9809-7fd46f4d5adb.png">

**Comment by ghost** [comment]
Fixed by https://github.com/vergecurrency/vWallet/pull/69
