### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by SwenVanZanten** [vergecurrency/vWallet#41]
Fillin all translations for each language..
The English one is the most updated and the development version.
The dutch is pretty updated overall.

Find people who can add additional translations.
Give them the JSON or translate it with them.
Enter their name in the credits panel.

**Comment by marpme** [comment]
Further Additions (Language list)

**European:**
- [x] Spanish (Done by [P1R](https://github.com/P1R))
- [x] Russian
- [ ] German
- [ ] Swedish
- [ ] Dutch
- [ ] Portugues
- [ ] French

**Asia:**
- [ ] Japanese
- [ ] Korean
- [ ] Turkish
- [ ] Indian

Please comment below if we miss any important (other) language

**Comment by marpme** [comment]
We will go the POEditor way, closing for now : )
