### ISSUE TITLE
Add the address book

### ISSUE THREAD

**Issue by SwenVanZanten** [vergecurrency/vWallet#42]
Add the address book with the following features.

- An address table with address and their label on it.
- Capability to delete it from the list with a button with a confirmation.
- An option to search through the list via label or part of address.
- The table need to be sortable via the label header.
- Capability to edit the label and the address from a modal after a double click.
- To add a new address you click the add button and it opens the add modal.

**Comment by marpme** [comment]
#54 uff, let's get this shit done, later on. There's no that much left on that one.
