### ISSUE TITLE
Implement the key commands

### ISSUE THREAD

**Issue by SwenVanZanten** [vergecurrency/vWallet#45]
Implement the key commands from the settings screen:

![schermafbeelding 2018-07-20 om 09 42 27](https://user-images.githubusercontent.com/3099122/42989923-75918092-8c01-11e8-99f5-92b2416691de.png)

Also enable for mac systems the `cmd + ,` command to open the settings panel.

**Comment by nickscrypto08** [comment]
Swen,

Pushed a commit.

**Comment by SwenVanZanten** [comment]
@nickscrypto08 great 🥇 😃 , now can you make a pull request of your commit?

Edit: @marpme already merged it into develop

**Comment by marpme** [comment]
Thank you @nickscrypto08, it's merged
