### ISSUE TITLE
Missing HTML file? Light Client.

### ISSUE THREAD

**Issue by Positivism** [vergecurrency/vWallet#64]
`Cannot GET /loading.html`
<img width="1004" alt="screen shot 2018-11-11 at 9 00 43 am" src="https://user-images.githubusercontent.com/35063339/48313902-65286e80-e590-11e8-8805-9a22608f87ff.png">
Self explanitory.
｢wdm｣: Compiled successfully.

```
$ node -v
v8.11.0
$ npm -v
5.6.0
```

**Comment by marpme** [comment]
Just refresh, didn't have time to check out what's wrong there
