### ISSUE TITLE
Automatically download the blockchain data when not available

### ISSUE THREAD

**Issue by marpme** [vergecurrency/vWallet#9]
Utilize: `https://verge-blockchain.com/blockchain/go.sh-Verge-Blockchain.zip` to download the newest blockchain.

* should be running within the loading process and should block it until done
* Status updates are needed to the front page tho

* Path on systems:
`~/.VERGE` - linux
`%appdata%/VERGE` - windows
`~/Library/Application\ Support/VERGE` - macOS 
* should be done once (first start), checks might be included

**Comment by marpme** [comment]
Example code, should be rewritten in NodeJS for cross-platform compatibility.
```bash
    wget --no-check-certificate https://verge-blockchain.com/blockchain/go.sh-Verge-Blockchain.zip

    #checksum
    sudo rm blockchain
    wget https://www.vergecurrency.com/checksums/blockchain
    md5sum go.sh-Verge-Blockchain.zip > md5
    checksum="$(grep $(cat md5) blockchain)"
    if [ -z "$checksum" ];
    then
       echo "Warning: MD5 is not matching"
    else
       echo "MD5 is matching...Success"
    fi

    unzip -o go.sh-Verge-Blockchain.zip -d ~/.VERGE
    sudo rm go.sh-Verge-Blockchain.zip
```

**Comment by ghost** [comment]
Hey guys, SwizzleSticks from core here.  I had written a windows script installer for 4.0.1 and 4.0.2.  It included the option to download the blockchain data. This is only for windows and I wrote it in CMD script, but here's my code if it helps at all....(not a dev, but write a lot of scripts).

echo ****Downloading Verge Blockchain data****
echo ****PLEASE BE PATIENT - THE BLOCKCHAIN DATA DOWNLOAD LARGE AND THE DOWNLOAD MAY TAKE SOME TIME DEPENDING ON YOUR INTERNET SPEEDS****
md %TEMP%\verge
REM powershell -Command "(New-Object Net.WebClient).DownloadFile('https://s1.verge-blockchain.com/Wallet_v4.x_Verge-Blockchain_2018-January-29.zip', '%TEMP%\verge\XVGBlockChain.zip')"
powershell -Command "Invoke-WebRequest https://s1.verge-blockchain.com/Wallet_v4.x_Verge-Blockchain_2018-January-29.zip -OutFile %TEMP%\verge\XVGBlockChain.zip"
cls
echo ****Download complete!  Unzipping and copying the Blockchain Data****
powershell -Command "expand-archive -literalpath %TEMP%\verge\XVGBlockChain.zip -destinationpath %TEMP%\verge\blockchain"
xcopy %TEMP%\verge\blockchain\*.* %userprofile%\AppData\Roaming\VERGE\ /e /c /d /y
cls
echo ****Congradulations, VergeQT Wallet v4.0.1.0-794660a has been installed, and the blockchain has been downloaded and put in place as well.
echo ****Press any key to exit the installer and begin using the Verge QT Wallet using the icon on the desktop****
echo.

**Comment by marpme** [comment]
This won't be needed anymore. As we don't need to download the entire blockchain anymore.
